// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5Cz29ShzABsf0xn_1m0oFYYbNuCtrZg',
    appId: '1:210644954904:web:0cabfea452cb75e083386d',
    messagingSenderId: '210644954904',
    projectId: 'weather-app-d5396',
    authDomain: 'weather-app-d5396.firebaseapp.com',
    storageBucket: 'weather-app-d5396.appspot.com',
    measurementId: 'G-D23TVG3744',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB6ujIG_Q-4kJSAsTfohlBv0nBkwGTBFk',
    appId: '1:210644954904:android:81a77e91326cb53683386d',
    messagingSenderId: '210644954904',
    projectId: 'weather-app-d5396',
    storageBucket: 'weather-app-d5396.appspot.com',
  );
}
